services:
  db:
    image: postgres:16
    container_name: cooperativa-db
    environment:
      POSTGRES_DB: governanca_cooperativa
      POSTGRES_USER: governanca_user
      POSTGRES_PASSWORD: governanca_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
